---
title: "Módulo 6: Inferencia Estadística"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
pak::pak(c("openxlsx","rstatix", "tidyverse", "nortest",
           "ggstatsplot", "performance", "pwr", 
           "pwr2", "simr"))

install.packages("openxlsx")
install.packages("rstatix")
install.packages("tidyverse")
install.packages("nortest")
install.packages("ggstatsplot")
install.packages("performance")
install.packages("pwr")
install.packages("pwr2")
install.packages("simr")

pak::pak("irwingss/masterX")
```

```{r}
library(tidyverse)
library(openxlsx)
library(performance)
library(ggstatsplot)
library(rstatix)
library(pwr)
library(pwr2)
library(simr)
library(nortest)
```

# Cargar bases de datos

```{r}
macro <- openxlsx::read.xlsx("bases/Khatri et al 2022 benthic macroinvertebrates assemblages.xlsx")
fire <- openxlsx::read.xlsx("bases/Fire 2024/fxh_complete_2021-2_dryad.xlsx")

macro <- openxlsx::read.xlsx(file.choose())
fire <- openxlsx::read.xlsx(file.choose())
```

# Pruebas de Normalidad

```{r}
# Ejemplo de clase Shapiro
shapiro.test(macro$Total.Catch) # No existen normalidad en los datos
length(macro$Total.Catch)

shapiro.test(fire$grass_biomass_21) #No existe normalidad

for (i in 10:13){
  normalidad <- shapiro.test(fire[,i]) # Test automatizado de normalidad
  print(normalidad)
}

# Ejemplo de clase Kolmogorov-Smirnov
ks.test(fire$grass_biomass_21, "pnorm", 
        mean(fire$grass_biomass_21, na.rm = TRUE),
        sd(fire$grass_biomass_21, na.rm = TRUE))

# Ejemplo de clase Normtest
nortest::lillie.test(fire$grass_biomass_21)
nortest::cvm.test(fire$grass_biomass_21)
nortest::ad.test(fire$grass_biomass_21)
nortest::sf.test(fire$grass_biomass_21)

# Ejemplo de clase masterX
masterX::NormTests(fire$grass_biomass_21)
masterX::NormTests(macro$Total.Catch)
```

```{r}
qqnorm(fire$grass_biomass_21)
qqline(fire$grass_biomass_21)

plot(density(fire$grass_biomass_21, na.rm = TRUE))

fire %>% 
  filter(fire == "Hot") %>% 
  pull(grass_biomass_21) %>% 
  density(na.rm = TRUE) %>% 
  plot()

```

```{r}
ggplot(fire, aes(sample = grass_biomass_21,
                 color = fire)) +
  geom_qq()+
  geom_qq_line() +
  facet_wrap(~fire) # AUTOMÁTICO
  # facet_grid(.~fire) # TODO LATERAL
    # facet_grid(fire~.) # TODo HACIA ABAJO
```


# Pruebas de T, Wilcoxon y Mann-Withney

```{r}

```

# Pruebas de ANOVA y Kruskal-Wallis

```{r}

```

# Prueba de Chi-cuadrado

```{r}

```
